#! /bin/bash

MUDMUX_INSTALL_PATH="$(pwd)"
DOCKER_CMD="docker run -ti --network=host -e TERM -v ${MUDMUX_INSTALL_PATH}:/home/mudmux mudmux-container:latest mm"
RCFILE=".profile"
touch "${MUDMUX_INSTALL_PATH}/logs/communications.log"

tmux new-session -s mudmux -d "bash --init-file <(echo '. $HOME/$RCFILE && sleep 1 && echo -e \"\033]50;SetProfile=med\a\" && ${DOCKER_CMD}')"
tmux split-window -h -p 25 "bash --init-file <(echo '. $HOME/$RCFILE && tail -f ${MUDMUX_INSTALL_PATH}/logs/communications.log')"
tmux split-window -v "bash --init-file <(echo '. $HOME/$RCFILE && emacs ${MUDMUX_INSTALL_PATH}/data/notes.txt')"
tmux -u -CC attach -t mudmux -d

echo -e "\033]50;SetProfile=Default\a"
