#! /bin/bash

DOCKER_CMD="docker run -ti --network=host -e TERM -v $(pwd):/home/med-scripts muxmed:latest ./med"
RCFILE=".profile"

tmux new-session -s medmux -d "bash --init-file <(echo '. $HOME/$RCFILE && sleep 1 && echo -e \"\033]50;SetProfile=med\a\" && ${DOCKER_CMD}')"
tmux split-window -h -p 25 "bash --init-file <(echo '. $HOME/$RCFILE && tail -f logs/communications.log')"
tmux split-window -v "bash --init-file <(echo '. $HOME/$RCFILE && emacs notes.txt')"
tmux -u -CC attach -t medmux -d

echo -e "\033]50;SetProfile=Default\a"